# Generated by Django 3.0.8 on 2020-08-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertermodel',
            name='extension',
        ),
        migrations.AddField(
            model_name='convertermodel',
            name='output_extension',
            field=models.CharField(choices=[('.mp4', 'Video Mp4'), ('.ts', 'Video TS'), ('.mp3', 'Audio Mp3'), ('.m4a', 'Audio M4a'), ('.flv', 'Flash Video'), ('.mkv', 'Video Matroska')], default='Video Mp4', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convertermodel',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('error', 'Error'), ('waiting', 'Waiting'), ('processing', 'Processing')], default='Video Mp4', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convertermodel',
            name='uploaded_extension',
            field=models.CharField(choices=[('.mp4', 'Video Mp4'), ('.ts', 'Video TS'), ('.mp3', 'Audio Mp3'), ('.m4a', 'Audio M4a'), ('.flv', 'Flash Video'), ('.mkv', 'Video Matroska')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
