# Generated by Django 3.0.8 on 2020-08-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20200821_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertermodel',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='convertermodel',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('error', 'Error'), ('waiting', 'Waiting'), ('processing', 'Processing'), ('unavailable', 'Unavailable')], default='waiting', max_length=20),
        ),
    ]
