# Generated by Django 3.0.8 on 2020-08-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('media', models.FileField(upload_to='demo/')),
                ('is_ready', models.BooleanField(default=False)),
                ('download_url', models.URLField()),
            ],
        ),
    ]
