# Generated by Django 3.0.8 on 2020-08-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200819_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='demots',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
